# Generated by Django 4.2.16 on 2024-09-13 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_band', models.CharField(max_length=50)),
                ('issue_size', models.CharField(max_length=100)),
                ('issue_type', models.CharField(max_length=50)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('rhp_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('drhp_pdf', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipo.company')),
            ],
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_market_price', models.FloatField()),
                ('current_return', models.FloatField()),
                ('ipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ipo.ipo')),
            ],
        ),
    ]
